#!/usr/bin/env python3
"""Export the CSV bonded-sphere template to a LIGGGHTS-INL multisphere file."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--particles",
        type=Path,
        default=Path("simulations/single_pebble/templates/sp_500_d1mm/particles.csv"),
        help="Input particles.csv generated by generate_bonded_sphere.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("simulations/single_pebble/SP-001/data/li4sio4_sp_500.multisphere"),
        help="Output LIGGGHTS-INL multisphere template.",
    )
    parser.add_argument(
        "--unit-scale",
        type=float,
        default=1.0e-3,
        help="Scale applied to CSV coordinates and radii. Default converts mm to m.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)

    with args.particles.open(newline="") as src, args.output.open("w") as dst:
        reader = csv.DictReader(src)
        for row in reader:
            x = float(row["x_mm"]) * args.unit_scale
            y = float(row["y_mm"]) * args.unit_scale
            z = float(row["z_mm"]) * args.unit_scale
            r = float(row["radius_mm"]) * args.unit_scale
            dst.write(f"{x:.12e} {y:.12e} {z:.12e} {r:.12e}\n")


if __name__ == "__main__":
    main()

